<?php

namespace Batchelor\Cache\Formatter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-09-01 at 17:17:59.
 */
class NativeFormatTest extends \PHPUnit_Framework_TestCase
{

        /**
         * @var NativeFormat
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
                $this->object = new NativeFormat;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
                
        }

        /**
         * @covers Batchelor\Cache\Formatter\None::onRead
         */
        public function testOnRead()
        {
                $expect = "test1";
                $actual = $this->object->onRead($expect);
                $this->assertNotNull($actual);
                $this->assertEquals($actual, $expect);

                $expect = false;
                $actual = $this->object->onRead($expect);
                $this->assertNotNull($actual);
                $this->assertEquals($actual, $expect);
        }

        /**
         * @covers Batchelor\Cache\Formatter\None::onSave
         */
        public function testOnSave()
        {
                $expect = "test1";
                $actual = $this->object->onSave($expect);
                $this->assertNotNull($actual);
                $this->assertEquals($actual, $expect);

                $expect = false;
                $actual = $this->object->onSave($expect);
                $this->assertNotNull($actual);
                $this->assertEquals($actual, $expect);
        }

        /**
         * @covers Batchelor\Cache\Formatter\None::setOptions
         */
        public function testSetOptions()
        {
                $this->object->setOptions([]);
                
                $expect = false;
                $actual = $this->object->getOptions();
                $this->assertNotNull($actual);
                $this->assertEquals($actual, $expect);
        }

        /**
         * @covers Batchelor\Cache\Formatter\None::getOptions
         */
        public function testGetOptions()
        {
                $expect = false;
                $actual = $this->object->getOptions();
                $this->assertNotNull($actual);
                $this->assertEquals($actual, $expect);
        }

}
