<?php

// 
// This array contains entries on this form:
// 
// [
//      'qeuue' => [
//              'name' => 'MyService',  // The class name
//              'args' => null          // Optional arguments.
//      ]
// ]
// 
// An entry can also be an already instantiated object. In this case simply
// replace data for class initialization with the object:
// 
// [
//      'qeuue' => new Qeuue()          // The queue service is always initialized
// ]


return [
];
