<?php

namespace Batchelor\Queue\Task\Execute;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-09-21 at 16:19:53.
 */
class ProcessTest extends \PHPUnit_Framework_TestCase
{

        /**
         * @var Process
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
                $this->object = new Process;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
                
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Process::__destruct
         * @todo   Implement test__destruct().
         */
        public function test__destruct()
        {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                    'This test has not been implemented yet.'
                );
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Process::signal
         * @todo   Implement testSignal().
         */
        public function testSignal()
        {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                    'This test has not been implemented yet.'
                );
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Process::suspend
         * @todo   Implement testSuspend().
         */
        public function testSuspend()
        {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                    'This test has not been implemented yet.'
                );
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Process::resume
         * @todo   Implement testResume().
         */
        public function testResume()
        {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                    'This test has not been implemented yet.'
                );
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Process::terminate
         * @todo   Implement testTerminate().
         */
        public function testTerminate()
        {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                    'This test has not been implemented yet.'
                );
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Process::getStreams
         * @todo   Implement testGetStreams().
         */
        public function testGetStreams()
        {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                    'This test has not been implemented yet.'
                );
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Process::getStream
         * @todo   Implement testGetStream().
         */
        public function testGetStream()
        {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                    'This test has not been implemented yet.'
                );
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Worker::getExitCode
         */
        public function testGetExitCode()
        {
                $expect = -1;
                $actual = $this->object->getExitCode();

                $this->assertNotNull($actual);
                $this->assertTrue(is_int($actual));
                $this->assertEquals($expect, $actual);

                $this->object->open();
                $this->object->close();

                $expect = 0;
                $actual = $this->object->getExitCode();

                $this->assertNotNull($actual);
                $this->assertTrue(is_int($actual));
                $this->assertEquals($expect, $actual);
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Worker::getStatus
         */
        public function testGetStatus()
        {
                $actual = $this->object->getStatus();
                $this->assertNotNull($actual);
                $this->assertTrue(is_object($actual));
                $this->assertTrue($actual instanceof Status);
                $this->assertTrue(is_null($actual->pid));

                $this->object->open();
                $actual = $this->object->getStatus();
                $this->assertNotNull($actual);
                $this->assertTrue(is_object($actual));
                $this->assertTrue($actual instanceof Status);
                $this->assertTrue(is_int($actual->pid));
                $this->assertTrue($actual->running);
                $this->assertFalse($actual->signaled);
                $this->assertFalse($actual->stopped);
                $this->assertTrue($actual->stopsig == 0);
                $this->assertTrue($actual->termsig == 0);
                $this->assertTrue($actual->exitcode == -1);
                $this->assertEquals($this->select->getCommand(), $actual->command);

                print_r($actual);

                $this->object->close();
                $actual = $this->object->getStatus();
                $this->assertNotNull($actual);
                $this->assertTrue(is_object($actual));
                $this->assertTrue($actual instanceof Status);
                $this->assertTrue(is_null($actual->pid));
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Process::isReadable
         * @todo   Implement testIsReadable().
         */
        public function testIsReadable()
        {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                    'This test has not been implemented yet.'
                );
        }

        /**
         * @covers Batchelor\Queue\Task\Execute\Process::close
         * @todo   Implement testClose().
         */
        public function testClose()
        {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                    'This test has not been implemented yet.'
                );
        }

}
