<?php

namespace Batchelor\Web;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-09-19 at 13:30:20.
 */
class DownloadTest extends \PHPUnit_Framework_TestCase
{

        /**
         * @var Download
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
                $this->object = new Download("http://localhost");
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
                
        }

        /**
         * @covers Batchelor\Web\Download::getContent
         */
        public function testGetContent()
        {
                $result = $this->object->getContent();

                $this->assertNotNull($result);
                $this->assertTrue(is_string($result));
        }

        /**
         * @covers Batchelor\Web\Download::getStream
         */
        public function testGetStream()
        {
                $handle = $this->object->getStream();

                $this->assertNotNull($handle);
                $this->assertTrue(is_resource($handle));

                while (($result = fread($handle, 10))) {
                        $this->assertNotNull($handle);
                        $this->assertTrue(is_resource($handle));

                        $this->assertNotNull($result);
                        $this->assertTrue(is_string($result));
                }
        }

        /**
         * @covers Batchelor\Web\Download::getChunk
         */
        public function testGetChunk()
        {
                $this->object->getStream();

                while (($result = $this->object->getChunk(10))) {
                        $this->assertNotNull($result);
                        $this->assertTrue(is_string($result));
                }
        }

        /**
         * @covers Batchelor\Web\Download::getLine
         */
        public function testGetLine()
        {
                $this->object->getStream();

                while (($result = $this->object->getLine())) {
                        $this->assertNotNull($result);
                        $this->assertTrue(is_string($result));
                }
        }

        /**
         * @covers Batchelor\Web\Download::isGood
         */
        public function testisGood()
        {
                $this->object->getStream();

                $this->assertTrue($this->object->isGood());
                $this->object->getContent();
                $this->assertFalse($this->object->isGood());
        }

}
